### ISSUE TITLE
What are attributes for Edge and Vertex class?

### ISSUE THREAD

**Issue by alexandrebouthinon** [YvesLongchamp/yveslongchampGraphJava#3]
No attibutes those classes in doc ? What are their specs ?

**Comment by YvesLongchamp** [comment]
An Edge has a table of vertices connected by him, and a graph where he is. A Vertex has a List (I didn't change that, sorry) of Edges, a color, a graph where he is, and can store an Object.

**Comment by alexandrebouthinon** [comment]
ok thank can you change the LIst to an simple array and tell me what are the constructors of each of them ?

**Comment by alexandrebouthinon** [comment]
I think an array of neighbour of a vertex is better than an array of edge

**Comment by alexandrebouthinon** [comment]
Itdoesn't matter i'll use my classes Edge and Vertex don't worry :)

**Comment by YvesLongchamp** [comment]
Ok, I will do the changes an other day.
